#!/usr/bin/env python3
"""
gen_strenc.py — generate AD_STRENC_* macros for the WhipAntiDebugger framework.

The framework encrypts every Nt*/Zw* / Win32 API name it touches via a
do { ... } while (0) macro that builds the buffer on the stack with
AD_ENC / AD_DECODE_BUF. Hand-typing those macros is error-prone (six
build warnings in the project history were duplicate definitions, one
was an off-by-one byte count). This script generates the macro body
from a list of API names so they always agree with the canonical
template.

Usage:
    python tools/gen_strenc.py NtClose NtCreateFile NtQuerySystemInformation
    python tools/gen_strenc.py --xor 0x4B NtClose
    python tools/gen_strenc.py --header NtClose NtCreateFile > out.h

Each API generates:

    #ifndef AD_STRENC_<Name>
    #define AD_STRENC_<Name>(buf)                                        \\
        do {                                                             \\
            const u8 _k = AD_STR_KEY(<key>);                             \\
            char buf##_e[<len+1>];                                       \\
            AD_ENC(buf##_e,  0, '<c0>', _k); ... AD_ENC(buf##_e, N, '<cN>', _k); \\
            AD_DECODE_BUF(buf##_e, <len>, _k);                           \\
            for (unsigned _ci = 0; _ci < <len+1>; _ci++) (buf)[_ci] = buf##_e[_ci]; \\
        } while (0)
    #endif

Keys are derived deterministically from a FNV-1a hash of the name so
multiple invocations on the same name produce identical output (no
spurious diffs). Pass --xor 0xNN to force a specific key.
"""

import argparse
import sys


def fnv1a_byte_key(name: str) -> int:
    """Deterministic per-name key derivation. Lower 8 bits of FNV-1a32."""
    h = 0x811C9DC5
    for c in name.encode("ascii"):
        h ^= c
        h = (h * 0x01000193) & 0xFFFFFFFF
    # Avoid 0x00 — that key would leave the encrypted buffer plaintext.
    k = h & 0xFF
    return k if k != 0 else 0x5A


def gen_macro(name: str, xor_key: int, indent: str = "    ") -> str:
    """Return the multi-line strenc macro for one API name."""
    n = len(name)
    out = []
    out.append(f"#ifndef AD_STRENC_{name}")
    # Pad the macro identifier line to a stable column for visual diff symmetry.
    pad = max(0, 60 - len(f"#define AD_STRENC_{name}(buf)"))
    out.append(f"#define AD_STRENC_{name}(buf){' ' * pad}\\")
    out.append(f"{indent}do {{                                                                     \\")
    out.append(f"{indent}    const u8 _k = AD_STR_KEY(0x{xor_key:02X});                                     \\")
    out.append(f"{indent}    char buf##_e[{n + 1}];                                                    \\")

    # Two AD_ENC per line, mirroring the existing hand-written macros.
    pairs = []
    for i in range(0, n, 2):
        a = f"AD_ENC(buf##_e, {i:2d}, '{name[i]}', _k);"
        if i + 1 < n:
            b = f"AD_ENC(buf##_e, {i + 1:2d}, '{name[i + 1]}', _k);"
            pairs.append(f"{indent}    {a} {b}       \\")
        else:
            pairs.append(f"{indent}    {a}                                       \\")
    out.extend(pairs)

    out.append(f"{indent}    AD_DECODE_BUF(buf##_e, {n}, _k);                                     \\")
    out.append(f"{indent}    for (unsigned _ci = 0; _ci < {n + 1}; _ci++) (buf)[_ci] = buf##_e[_ci];  \\")
    out.append(f"{indent}}} while (0)")
    out.append("#endif")
    return "\n".join(out)


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate AD_STRENC_* macros for WhipAntiDebugger.",
    )
    p.add_argument("names", nargs="+", help="API names to generate macros for")
    p.add_argument("--xor", type=lambda s: int(s, 0),
                   help="Force this XOR key for every name (default: per-name FNV-1a)")
    p.add_argument("--header", action="store_true",
                   help="Wrap output in an include-guarded header skeleton")
    args = p.parse_args()

    blocks = []
    for name in args.names:
        if not name.isidentifier():
            print(f"error: '{name}' is not a valid C identifier", file=sys.stderr)
            return 2
        key = args.xor if args.xor is not None else fnv1a_byte_key(name)
        blocks.append(gen_macro(name, key))

    body = "\n\n".join(blocks)
    if args.header:
        guard = "ANTIDEBUG_STRENC_GENERATED_H"
        print(f"// Generated by tools/gen_strenc.py — DO NOT EDIT BY HAND.")
        print(f"#ifndef {guard}")
        print(f"#define {guard}\n")
        print('#include "../core/types.h"')
        print('#include "../core/string_encrypt.h"\n')
        print(body)
        print(f"\n#endif // {guard}")
    else:
        print(body)

    return 0


if __name__ == "__main__":
    sys.exit(main())
