#pragma once
#include <windows.h>

inline BOOL ENABLE_TLS_CHECKS = FALSE;
inline BOOL ENABLE_DEBUG_CHECKS = FALSE;
inline BOOL ENABLE_INJECTION_CHECKS = FALSE;
inline BOOL ENABLE_GEN_SANDBOX_CHECKS = FALSE;
inline BOOL ENABLE_VBOX_CHECKS = FALSE;
inline BOOL ENABLE_VMWARE_CHECKS = FALSE;
inline BOOL ENABLE_VPC_CHECKS = FALSE;
inline BOOL ENABLE_QEMU_CHECKS = FALSE;
inline BOOL ENABLE_KVM_CHECKS = FALSE;
inline BOOL ENABLE_XEN_CHECKS = FALSE;
inline BOOL ENABLE_WINE_CHECKS = FALSE;
inline BOOL ENABLE_PARALLELS_CHECKS = FALSE;
inline BOOL ENABLE_HYPERV_CHECKS = FALSE;
inline BOOL ENABLE_CODE_INJECTIONS = FALSE;
inline BOOL ENABLE_TIMING_ATTACKS = FALSE;
inline BOOL ENABLE_DUMPING_CHECK = FALSE;
inline BOOL ENABLE_ANALYSIS_TOOLS_CHECK = FALSE;
inline BOOL ENABLE_ANTI_DISASSM_CHECKS = FALSE;

inline void EnableDefaultChecks() {
    ENABLE_TLS_CHECKS = TRUE;
    ENABLE_DEBUG_CHECKS = TRUE;
    ENABLE_INJECTION_CHECKS = TRUE;
    ENABLE_GEN_SANDBOX_CHECKS = TRUE;
    ENABLE_VBOX_CHECKS = TRUE;
    ENABLE_VMWARE_CHECKS = TRUE;
    ENABLE_VPC_CHECKS = TRUE;
    ENABLE_QEMU_CHECKS = TRUE;
    ENABLE_KVM_CHECKS = TRUE;
    ENABLE_XEN_CHECKS = TRUE;
    ENABLE_WINE_CHECKS = TRUE;
    ENABLE_PARALLELS_CHECKS = TRUE;
    ENABLE_HYPERV_CHECKS = TRUE;
    ENABLE_TIMING_ATTACKS = TRUE;
    ENABLE_DUMPING_CHECK = TRUE;
    ENABLE_ANALYSIS_TOOLS_CHECK = TRUE;
    ENABLE_ANTI_DISASSM_CHECKS = TRUE;
}

DWORD WINAPI BackgroundMonitoringThread(LPVOID lpParam);
