#pragma once

#include "TrackedString.h"
#include <cstring>

#define TRACKED_STATIC_STRING(name, str) \
    inline const char* name() { \
        constexpr size_t len = sizeof(str) - 1; \
        constexpr uint8_t xorKey = static_cast<uint8_t>((__COUNTER__ * 0x9e3779b9) ^ (__LINE__ * 0x517cc1b7)); \
        \
        struct EncryptedData { \
            char encrypted[len + 1]; \
            \
            constexpr EncryptedData() : encrypted{} { \
                for (size_t i = 0; i < len; ++i) { \
                    encrypted[i] = str[i] ^ (xorKey + static_cast<uint8_t>(i)); \
                } \
                encrypted[len] = '\0'; \
            } \
            \
            void decrypt(char* out) const { \
                for (size_t i = 0; i < len; ++i) { \
                    out[i] = encrypted[i] ^ (xorKey + static_cast<uint8_t>(i)); \
                } \
                out[len] = '\0'; \
            } \
        }; \
        \
        static EncryptedData* encryptedPtr = []() -> EncryptedData* { \
            auto* ptr = static_cast<EncryptedData*>(TrackedStringRegistry::instance().allocate(sizeof(EncryptedData))); \
            if (ptr) { \
                new (ptr) EncryptedData(); \
                TrackedStringRegistry::instance().track(reinterpret_cast<char*>(ptr), sizeof(EncryptedData), true); \
            } \
            return ptr; \
        }(); \
        \
        static char* decryptBuffer = []() -> char* { \
            auto* ptr = static_cast<char*>(TrackedStringRegistry::instance().allocate(len + 1)); \
            if (ptr) { \
                TrackedStringRegistry::instance().track(ptr, len + 1, true); \
            } \
            return ptr; \
        }(); \
        \
        static bool decrypted_ = false; \
        if (!decrypted_ && encryptedPtr && decryptBuffer) { \
            encryptedPtr->decrypt(decryptBuffer); \
            decrypted_ = true; \
        } \
        return decryptBuffer; \
    }

namespace Strings {

    TRACKED_STATIC_STRING(windowTitle, "Whip Client v0.7")
    TRACKED_STATIC_STRING(lifetimeSuffix, " : lifetime")
    TRACKED_STATIC_STRING(titlebarId, "titlebar")
    TRACKED_STATIC_STRING(sidebarId, "sidebar")
    TRACKED_STATIC_STRING(contentId, "content")
    TRACKED_STATIC_STRING(headerId, "header")
    TRACKED_STATIC_STRING(buttonsId, "buttons")
    TRACKED_STATIC_STRING(dropdownContentId, "dropdown_content")
    TRACKED_STATIC_STRING(iconText, "I")
    TRACKED_STATIC_STRING(iconGear, "F")
    TRACKED_STATIC_STRING(iconDown, "A")
    TRACKED_STATIC_STRING(createConfigText, "Create Config")

    TRACKED_STATIC_STRING(gdi32Dll, "Gdi32.dll")
    TRACKED_STATIC_STRING(swapBuffersFunc, "SwapBuffers")
    TRACKED_STATIC_STRING(lwjglWindow, "LWJGL")
    TRACKED_STATIC_STRING(glfwWindow, "GLFW30")
    TRACKED_STATIC_STRING(ws2_32Dll, "ws2_32.dll")

    TRACKED_STATIC_STRING(authTransportKey, "6!NYRYP$xcJ7gYTLnMn4g?eLY7fX&tqyyQG@j9sf")
    TRACKED_STATIC_STRING(authServerIP, "51.178.31.94")
    TRACKED_STATIC_STRING(authServerPubkeyFingerprint, "b69e1443486353002c887843f3fe2053c0287365885d69b79dc895edc207b2fa")
    TRACKED_STATIC_STRING(authXorKey1, "secret1337@@667ekipafond")
    TRACKED_STATIC_STRING(authXorKey2, "SiLePseudoC'estXenoticC'estAdieuxHiHi")
    TRACKED_STATIC_STRING(authHeartbeatKey, "GuiNoHookSwapBuffer@@1348447")
    TRACKED_STATIC_STRING(authDllEncryptionKey, "dll-encryption-key-v1")

    TRACKED_STATIC_STRING(base64Upper, "ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    TRACKED_STATIC_STRING(base64Lower, "abcdefghijklmnopqrstuvwxyz")
    TRACKED_STATIC_STRING(base64Digits, "0123456789+/")

    TRACKED_STATIC_STRING(errP256KeypairFailed, "error: failed to generate P-256 keypair")
    TRACKED_STATIC_STRING(errConnectionFailed, "error: connection failed")
    TRACKED_STATIC_STRING(errRequestFailed, "error: request failed")
    TRACKED_STATIC_STRING(errReceiveFailed, "error: receive failed")
    TRACKED_STATIC_STRING(errInvalidResponseSize, "error: invalid response size")
    TRACKED_STATIC_STRING(errAuthFailed, "error: authentication failed")
    TRACKED_STATIC_STRING(errTruncatedResponse, "error: truncated response")
    TRACKED_STATIC_STRING(errInvalidResponseFormat, "error: invalid response format")
    TRACKED_STATIC_STRING(errFingerprintMismatch, "error: SECURITY ALERT - Server fingerprint mismatch")
    TRACKED_STATIC_STRING(errInvalidServerTimestamp, "error: invalid server timestamp")
    TRACKED_STATIC_STRING(errMalformedTimestamp, "error: malformed timestamp")
    TRACKED_STATIC_STRING(errTimestampVerifyFailed, "error: timestamp verification failed")
    TRACKED_STATIC_STRING(errInvalidSignature, "error: Invalid signature - MITM or corruption detected")
    TRACKED_STATIC_STRING(errECDHFailed, "error: ECDH failed")
    TRACKED_STATIC_STRING(errHKDFFailed, "error: HKDF failed")
    TRACKED_STATIC_STRING(errInvalidCiphertext, "error: invalid ciphertext")
    TRACKED_STATIC_STRING(errInvalidNonce, "error: invalid nonce")
    TRACKED_STATIC_STRING(errInvalidAuthTag, "error: invalid auth tag")
    TRACKED_STATIC_STRING(errGCMAuthFailed, "error: GCM authentication failed")
    TRACKED_STATIC_STRING(errFailedParseVersions, "error: failed to parse versions")
    TRACKED_STATIC_STRING(errInvalidMappingResponseSize, "error: invalid mapping response size")
    TRACKED_STATIC_STRING(errResponseTooSmall, "error: Response too small")
    TRACKED_STATIC_STRING(errMissingCredentials, "error: missing credentials")
    TRACKED_STATIC_STRING(errInvalidResponse, "error: invalid response")
    TRACKED_STATIC_STRING(errInvalidDataSize, "error: invalid data size")
    TRACKED_STATIC_STRING(errInvalidConfigsDataSize, "error: invalid configs data size")

    TRACKED_STATIC_STRING(statusVersionsLoaded, "versions_loaded")
    TRACKED_STATIC_STRING(statusConfigCreated, "config_created")
    TRACKED_STATIC_STRING(statusConfigLoaded, "config_loaded")
    TRACKED_STATIC_STRING(statusConfigDeleted, "config_deleted")
    TRACKED_STATIC_STRING(statusConfigsListed, "configs_listed")
    TRACKED_STATIC_STRING(statusConfigModified, "config_modified")
    TRACKED_STATIC_STRING(statusPlayerInfoSuccess, "player_info_success")

    TRACKED_STATIC_STRING(debugLoginPart2, "[loginPart2]")
    TRACKED_STATIC_STRING(debugGetPlayerInfo, "[getPlayerInfo]")
    TRACKED_STATIC_STRING(debugTickLocker, "[TickLocker]")

    TRACKED_STATIC_STRING(cmdTaskKill, "taskkill /F /PID ")

    TRACKED_STATIC_STRING(catCombat, "Combat")
    TRACKED_STATIC_STRING(catVisual, "Visual")
    TRACKED_STATIC_STRING(catMovement, "Movement")
    TRACKED_STATIC_STRING(catMisc, "Misc")
    TRACKED_STATIC_STRING(catNetwork, "Network")
    TRACKED_STATIC_STRING(catConfig, "Config")
    TRACKED_STATIC_STRING(catSetting, "Setting")
    TRACKED_STATIC_STRING(catTest, "Test")
    TRACKED_STATIC_STRING(catBackend, "Backend")
    TRACKED_STATIC_STRING(catUnknown, "Unknown")

    TRACKED_STATIC_STRING(modNone, "None")
    TRACKED_STATIC_STRING(modAimAssist, "AimAssist")
    TRACKED_STATIC_STRING(modAntiBot, "AntiBot")
    TRACKED_STATIC_STRING(modAutoClicker, "AutoClicker")
    TRACKED_STATIC_STRING(modAutoRefill, "AutoRefill")
    TRACKED_STATIC_STRING(modBacktrack, "Backtrack")
    TRACKED_STATIC_STRING(modBlockHit, "BlockHit")
    TRACKED_STATIC_STRING(modFakeLag, "FakeLag")
    TRACKED_STATIC_STRING(modCriticals, "Criticals")
    TRACKED_STATIC_STRING(modHitSelect, "HitSelect")
    TRACKED_STATIC_STRING(modKeepSprint, "KeepSprint")
    TRACKED_STATIC_STRING(modLagRange, "LagRange")
    TRACKED_STATIC_STRING(modTimeRange, "TimeRange")
    TRACKED_STATIC_STRING(modHitThroughBlock, "HitThroughBlock")
    TRACKED_STATIC_STRING(modMoreKB, "MoreKB")
    TRACKED_STATIC_STRING(modPerfectHit, "PerfectHit")
    TRACKED_STATIC_STRING(modPiercing, "Piercing")
    TRACKED_STATIC_STRING(modTimerRangeV1, "TimerRangeV1")
    TRACKED_STATIC_STRING(modTimerRangeV2, "TimerRangeV2")
    TRACKED_STATIC_STRING(modAutoRodV1, "AutoRodV1")
    TRACKED_STATIC_STRING(modSmartClicking, "SmartClicking")
    TRACKED_STATIC_STRING(modThrow, "Throw")
    TRACKED_STATIC_STRING(modVelocity, "Velocity")
    TRACKED_STATIC_STRING(modWTap, "WTap")
    TRACKED_STATIC_STRING(modBlink, "Blink")
    TRACKED_STATIC_STRING(modBtAugustus, "BTaugustus")
    TRACKED_STATIC_STRING(modAutoScroll, "AutoScroll")
    TRACKED_STATIC_STRING(modAutoTool, "AutoTool")
    TRACKED_STATIC_STRING(modBowBoost, "BowBoost")
    TRACKED_STATIC_STRING(modBowAimbot, "BowAimbot")
    TRACKED_STATIC_STRING(modChestStealer, "ChestStealer")
    TRACKED_STATIC_STRING(modInvManager, "InvManager")
    TRACKED_STATIC_STRING(modFastBreak, "FastBreak")
    TRACKED_STATIC_STRING(modFastPlace, "FastPlace")
    TRACKED_STATIC_STRING(modNoC07, "NoC07")
    TRACKED_STATIC_STRING(modNoItemRelease, "NoItemRelease")
    TRACKED_STATIC_STRING(modPotCounter, "PotCounter")
    TRACKED_STATIC_STRING(modRightClicker, "RightClicker")
    TRACKED_STATIC_STRING(modThrowRod, "ThrowRod")
    TRACKED_STATIC_STRING(modTickLocker, "TickLocker")
    TRACKED_STATIC_STRING(modBridgeAssist, "BridgeAssist")
    TRACKED_STATIC_STRING(modInvWalk, "InvWalk")
    TRACKED_STATIC_STRING(modNoJumpDelay, "NoJumpDelay")
    TRACKED_STATIC_STRING(modQuickAccel, "QuickAccel")
    TRACKED_STATIC_STRING(modQuickStop, "QuickStop")
    TRACKED_STATIC_STRING(modNoSlow, "NoSlow")
    TRACKED_STATIC_STRING(modSprint, "Sprint")
    TRACKED_STATIC_STRING(modScaffold, "Scaffold")
    TRACKED_STATIC_STRING(modSnapTap, "SnapTap")
    TRACKED_STATIC_STRING(modFastStop, "FastStop")
    TRACKED_STATIC_STRING(snapTapAxisBoth, "Both")
    TRACKED_STATIC_STRING(snapTapAxisStrafe, "Strafe")
    TRACKED_STATIC_STRING(snapTapAxisFwdBack, "Fwd/Back")
    TRACKED_STATIC_STRING(modSprintReset, "SprintReset")
    TRACKED_STATIC_STRING(modFullBright, "FullBright")
    TRACKED_STATIC_STRING(modFriends, "Friends")
    TRACKED_STATIC_STRING(modEnemies, "Enemies")
    TRACKED_STATIC_STRING(modGUI, "GUI")
    TRACKED_STATIC_STRING(modSettings, "Settings")
    TRACKED_STATIC_STRING(modWeapons, "Weapons")
    TRACKED_STATIC_STRING(modPrivate, "Private")
    TRACKED_STATIC_STRING(modPublic, "Public")
    TRACKED_STATIC_STRING(modArrayList, "ArrayList")
    TRACKED_STATIC_STRING(modWatermark, "Watermark")
    TRACKED_STATIC_STRING(modESP, "ESP")
    TRACKED_STATIC_STRING(modStorageESP, "StorageESP")
    TRACKED_STATIC_STRING(modChams, "Chams")
    TRACKED_STATIC_STRING(modTrajectories, "Trajectories")
    TRACKED_STATIC_STRING(modItemESP, "ItemESP")
    TRACKED_STATIC_STRING(modPlayerESP, "PlayerESP")
    TRACKED_STATIC_STRING(modBlockESP, "BlockESP")
    TRACKED_STATIC_STRING(modHUD, "HUD")
    TRACKED_STATIC_STRING(modNameTag, "NameTag")
    TRACKED_STATIC_STRING(modNotification, "Notification")
    TRACKED_STATIC_STRING(modTickLockerVisual, "TICK Locker VISUAL")
    TRACKED_STATIC_STRING(modTracer, "Tracer")
    TRACKED_STATIC_STRING(modHitHealCounter, "Counters")
    TRACKED_STATIC_STRING(modAutoClutch, "AutoClutch")
    TRACKED_STATIC_STRING(modInvalid, "Invalid")

    TRACKED_STATIC_STRING(optDynamic, "Dynamic")
    TRACKED_STATIC_STRING(optStatic, "Static")
    TRACKED_STATIC_STRING(optEnabled, "Enabled")
    TRACKED_STATIC_STRING(optDisabled, "Disabled")

    TRACKED_STATIC_STRING(modeLegit, "Legit")
    TRACKED_STATIC_STRING(modeBlatant, "Blatant")
    TRACKED_STATIC_STRING(modeSemiBlatant, "Semi Blatant")
    TRACKED_STATIC_STRING(modeNormal, "Normal")
    TRACKED_STATIC_STRING(modeTimer, "Timer")
    TRACKED_STATIC_STRING(modePacket, "Packet")
    TRACKED_STATIC_STRING(modeReverse, "Reverse")
    TRACKED_STATIC_STRING(modeJump, "Jump")
    TRACKED_STATIC_STRING(modeNoItemRelease, "NoItemRelease")
    TRACKED_STATIC_STRING(modeNoSlow, "NoSlow")
    TRACKED_STATIC_STRING(modeJitter, "Jitter")
    TRACKED_STATIC_STRING(modeButterfly, "Butterfly")
    TRACKED_STATIC_STRING(modeAgro, "Agro")
    TRACKED_STATIC_STRING(modeFly, " Fly")
    TRACKED_STATIC_STRING(modeDelay, "Delay")
    TRACKED_STATIC_STRING(modeClick, "Click")
    TRACKED_STATIC_STRING(modeSolo, "Solo")
    TRACKED_STATIC_STRING(modeTeam, "Team")

    TRACKED_STATIC_STRING(prioDistance, "Distance")
    TRACKED_STATIC_STRING(prioFov, "Fov")
    TRACKED_STATIC_STRING(prioHurttime, "Hurttime")

    TRACKED_STATIC_STRING(itemPotion, "Potion")
    TRACKED_STATIC_STRING(itemSoup, "Soup")
    TRACKED_STATIC_STRING(itemSword, "Sword")
    TRACKED_STATIC_STRING(itemBow, "Bow")
    TRACKED_STATIC_STRING(itemAxe, "Axe")
    TRACKED_STATIC_STRING(itemConsumable, "Consumable")
    TRACKED_STATIC_STRING(itemAll, "All")

    TRACKED_STATIC_STRING(render2D, "2D")
    TRACKED_STATIC_STRING(render3D, "3D")
    TRACKED_STATIC_STRING(renderBoth, "Both")
    TRACKED_STATIC_STRING(renderOutline, "Outline")
    TRACKED_STATIC_STRING(renderFill, "Fill")

    TRACKED_STATIC_STRING(colorChroma, "Chroma")
    TRACKED_STATIC_STRING(colorWeave, "Weave")
    TRACKED_STATIC_STRING(colorGradient, "Gradient")
    TRACKED_STATIC_STRING(colorAstolfo, "Astolfo")
    TRACKED_STATIC_STRING(colorFade, "Fade")

    TRACKED_STATIC_STRING(posBottomRight, "Bottom Right")
    TRACKED_STATIC_STRING(posBottomLeft, "Bottom Left")
    TRACKED_STATIC_STRING(posTopLeft, "Top Left")
    TRACKED_STATIC_STRING(posTopRight, "Top Right")

    TRACKED_STATIC_STRING(storageChest, "Chest")
    TRACKED_STATIC_STRING(storageEnderChest, "Ender Chest")
    TRACKED_STATIC_STRING(storageTrappedChest, "Trapped Chest")
    TRACKED_STATIC_STRING(storageFurnace, "Furnace")
    TRACKED_STATIC_STRING(storageDispenser, "Dispenser")
    TRACKED_STATIC_STRING(storageDropper, "Dropper")
    TRACKED_STATIC_STRING(storageHopper, "Hopper")
    TRACKED_STATIC_STRING(storageGeneric, "Storage")

    TRACKED_STATIC_STRING(storageChestLower, "chest")
    TRACKED_STATIC_STRING(storageEnderChestLower, "ender_chest")
    TRACKED_STATIC_STRING(storageTrappedChestLower, "trapped_chest")
    TRACKED_STATIC_STRING(storageFurnaceLower, "furnace")
    TRACKED_STATIC_STRING(storageDispenserLower, "dispenser")
    TRACKED_STATIC_STRING(storageDropperLower, "dropper")
    TRACKED_STATIC_STRING(storageHopperLower, "hopper")

    TRACKED_STATIC_STRING(tileEntityChest, "TileEntityChest")
    TRACKED_STATIC_STRING(tileEntityEnderChest, "TileEntityEnderChest")
    TRACKED_STATIC_STRING(tileEntityFurnace, "TileEntityFurnace")
    TRACKED_STATIC_STRING(tileEntityDispenser, "TileEntityDispenser")
    TRACKED_STATIC_STRING(tileEntityDropper, "TileEntityDropper")
    TRACKED_STATIC_STRING(tileEntityHopper, "TileEntityHopper")

    TRACKED_STATIC_STRING(btnClear, "Clear")
    TRACKED_STATIC_STRING(btnClearAllFriends, "Clear All Friends")
    TRACKED_STATIC_STRING(btnClearAllEnemies, "Clear All Enemies")
    TRACKED_STATIC_STRING(btnAddEnemy, "Add Enemy")
    TRACKED_STATIC_STRING(btnRemove, "Remove")
    TRACKED_STATIC_STRING(btnRemoveLastFriend, "Remove last friend")
    TRACKED_STATIC_STRING(lblAutoSwitch, "Auto Switch")
    TRACKED_STATIC_STRING(lblReturnToSlot, "Return To Slot")
    TRACKED_STATIC_STRING(lblBind, "Bind")
    TRACKED_STATIC_STRING(lblSpeed, "Speed")
    TRACKED_STATIC_STRING(lblSmartMode, "Smart Mode")
    TRACKED_STATIC_STRING(lblDoubleThrow, "Double Throw")
    TRACKED_STATIC_STRING(lblDoubleUse, "Double Use")
    TRACKED_STATIC_STRING(lblAutoDrop, "Auto Drop")
    TRACKED_STATIC_STRING(lblEnableHealth, "Enable Health")
    TRACKED_STATIC_STRING(lblEnableSoup, "Enable soup")
    TRACKED_STATIC_STRING(lblEnableDebuff, "Enable Debuff")
    TRACKED_STATIC_STRING(lblEnablePearl, "Enable Pearl")
    TRACKED_STATIC_STRING(lblAccentColor, "Accent Color")
    TRACKED_STATIC_STRING(lblScale, "Scale")
    TRACKED_STATIC_STRING(lblHide, "Hide")
    TRACKED_STATIC_STRING(lblDestruct, "Destruct")
    TRACKED_STATIC_STRING(lblPanic, "Panic")
    TRACKED_STATIC_STRING(lblSettings, "Settings")
    TRACKED_STATIC_STRING(lblEnemiesInput, "Enemies Input")
    TRACKED_STATIC_STRING(lblEnemiesList, "Enemies List")
    TRACKED_STATIC_STRING(lblUnknown, "Unknown")
    TRACKED_STATIC_STRING(lblEnable, "Enable")
    TRACKED_STATIC_STRING(lblName, "Name")
    TRACKED_STATIC_STRING(lblDescription, "Description")
    TRACKED_STATIC_STRING(btnCreate, "Create")
    TRACKED_STATIC_STRING(btnCancel, "Cancel")
    TRACKED_STATIC_STRING(lblShowInArrayList, "Show in ArrayList")
    TRACKED_STATIC_STRING(lblConfigName, "Configuration Name")
    TRACKED_STATIC_STRING(lblDescOptional, "Description (Optional)")
    TRACKED_STATIC_STRING(lblFov, "fov")
    TRACKED_STATIC_STRING(lblDistance, "distance")
    TRACKED_STATIC_STRING(lblPlayers, "Players")
    TRACKED_STATIC_STRING(lblMobs, "Mobs")
    TRACKED_STATIC_STRING(lblAverage, "Average")

    TRACKED_STATIC_STRING(secThrowHealth, "ThrowHealth")
    TRACKED_STATIC_STRING(secThrowSoup, "ThrowSoup")
    TRACKED_STATIC_STRING(secThrowDebuff, "ThrowDebuff")
    TRACKED_STATIC_STRING(secThrowPearl, "ThrowPearl")
    TRACKED_STATIC_STRING(secSettings, "Settings")
    TRACKED_STATIC_STRING(secSettings1, "Settings ")
    TRACKED_STATIC_STRING(secSettings2, "Settings  ")
    TRACKED_STATIC_STRING(secSettings3, "Settings   ")
    TRACKED_STATIC_STRING(secSettings4, "Settings    ")

    TRACKED_STATIC_STRING(msgTargetBlockCleared, "Target block cleared")
    TRACKED_STATIC_STRING(msgTargetBlockUpdated, "Target block updated")
    TRACKED_STATIC_STRING(msgSameBlockTargeted, "Same block already targeted")
    TRACKED_STATIC_STRING(msgNoBlockTargeted, "No block targeted")

    TRACKED_STATIC_STRING(msgNoFriendsToRemove, "No friends to remove")
    TRACKED_STATIC_STRING(msgNoEnemiesToRemove, "No enemies to remove")
    TRACKED_STATIC_STRING(msgAddedOffline, " added (offline)")
    TRACKED_STATIC_STRING(msgEnemyAdded, " enemy added")
    TRACKED_STATIC_STRING(msgEnemyRemoved, " enemy removed")
    TRACKED_STATIC_STRING(msgEnemyAddedCap, "Enemy added")
    TRACKED_STATIC_STRING(msgEnemyRemovedCap, "Enemy removed")
    TRACKED_STATIC_STRING(msgFriendAdded, " friend added")
    TRACKED_STATIC_STRING(msgFriendRemoved, " friend removed")
    TRACKED_STATIC_STRING(msgFriendAddedCap, "Friend added")
    TRACKED_STATIC_STRING(msgFriendRemovedCap, "Friend removed")
    TRACKED_STATIC_STRING(msgEnemiesRemoved, " enemies removed")
    TRACKED_STATIC_STRING(msgEnemiesAdded, " enemies added")
    TRACKED_STATIC_STRING(msgFriendsRemoved, " friends removed")
    TRACKED_STATIC_STRING(msgFriendsAdded, " friends added")

    TRACKED_STATIC_STRING(msgConfigLoadedSuccess, " loaded successfully.")
    TRACKED_STATIC_STRING(msgConfigCreatedSuccess, " created successfully.")
    TRACKED_STATIC_STRING(msgConfigDeletedSuccess, " deleted successfully.")
    TRACKED_STATIC_STRING(msgConfigModifiedSuccess, " modified successfully.")
    TRACKED_STATIC_STRING(msgConfigLoadFailed, "Failed to load config: ")
    TRACKED_STATIC_STRING(msgConfigCreateFailed, "Failed to create config: ")
    TRACKED_STATIC_STRING(msgConfigDeleteFailed, "Failed to delete config: ")
    TRACKED_STATIC_STRING(msgConfigModifyFailed, "Failed to modify config: ")
    TRACKED_STATIC_STRING(msgConfigCreateServerFailed, "Failed to create config on server")
    TRACKED_STATIC_STRING(msgConfigDeleteServerFailed, "Failed to delete config from server")
    TRACKED_STATIC_STRING(msgConfigUpdateServerFailed, "Failed to update config on server")

    TRACKED_STATIC_STRING(cfgDefaultDescription, "Server Config")
    TRACKED_STATIC_STRING(cfgDefaultAuthor, "User")

    TRACKED_STATIC_STRING(msgPressF4ToOpenGui, "Press F4 to open the gui")
    TRACKED_STATIC_STRING(msgThrowDebuffUsed, "ThrowDebuff used")
    TRACKED_STATIC_STRING(msgThrowPearlUsed, "ThrowPearl used")
    TRACKED_STATIC_STRING(msgThrowPotUsed, "ThrowPot used")
    TRACKED_STATIC_STRING(msgThrowSoupUsed, "ThrowSoup used")

    TRACKED_STATIC_STRING(flagHealth, "Health ")
    TRACKED_STATIC_STRING(flagSoup, "Soup ")
    TRACKED_STATIC_STRING(flagDebuff, "Debuff ")
    TRACKED_STATIC_STRING(flagPearl, "Pearl")

    TRACKED_STATIC_STRING(statusEnabled, "enabled")
    TRACKED_STATIC_STRING(statusDisabled, "disabled")

    TRACKED_STATIC_STRING(pktS0EPacketSpawnObject, "S0EPacketSpawnObject")
    TRACKED_STATIC_STRING(pktS11PacketSpawnExperienceOrb, "S11PacketSpawnExperienceOrb")
    TRACKED_STATIC_STRING(pktS2CPacketSpawnGlobalEntity, "S2CPacketSpawnGlobalEntity")
    TRACKED_STATIC_STRING(pktS0FPacketSpawnMob, "S0FPacketSpawnMob")
    TRACKED_STATIC_STRING(pktS3BPacketScoreboardObjective, "S3BPacketScoreboardObjective")
    TRACKED_STATIC_STRING(pktS10PacketSpawnPainting, "S10PacketSpawnPainting")
    TRACKED_STATIC_STRING(pktS0CPacketSpawnPlayer, "S0CPacketSpawnPlayer")
    TRACKED_STATIC_STRING(pktS0BPacketAnimation, "S0BPacketAnimation")
    TRACKED_STATIC_STRING(pktS37PacketStatistics, "S37PacketStatistics")
    TRACKED_STATIC_STRING(pktS25PacketBlockBreakAnim, "S25PacketBlockBreakAnim")
    TRACKED_STATIC_STRING(pktS36PacketSignEditorOpen, "S36PacketSignEditorOpen")
    TRACKED_STATIC_STRING(pktS35PacketUpdateTileEntity, "S35PacketUpdateTileEntity")
    TRACKED_STATIC_STRING(pktS24PacketBlockAction, "S24PacketBlockAction")
    TRACKED_STATIC_STRING(pktS23PacketBlockChange, "S23PacketBlockChange")
    TRACKED_STATIC_STRING(pktS02PacketChat, "S02PacketChat")
    TRACKED_STATIC_STRING(pktS3APacketTabComplete, "S3APacketTabComplete")
    TRACKED_STATIC_STRING(pktS22PacketMultiBlockChange, "S22PacketMultiBlockChange")
    TRACKED_STATIC_STRING(pktS34PacketMaps, "S34PacketMaps")
    TRACKED_STATIC_STRING(pktS32PacketConfirmTransaction, "S32PacketConfirmTransaction")
    TRACKED_STATIC_STRING(pktS2EPacketCloseWindow, "S2EPacketCloseWindow")
    TRACKED_STATIC_STRING(pktS30PacketWindowItems, "S30PacketWindowItems")
    TRACKED_STATIC_STRING(pktS2DPacketOpenWindow, "S2DPacketOpenWindow")
    TRACKED_STATIC_STRING(pktS31PacketWindowProperty, "S31PacketWindowProperty")
    TRACKED_STATIC_STRING(pktS2FPacketSetSlot, "S2FPacketSetSlot")
    TRACKED_STATIC_STRING(pktS3FPacketCustomPayload, "S3FPacketCustomPayload")
    TRACKED_STATIC_STRING(pktS0APacketUseBed, "S0APacketUseBed")
    TRACKED_STATIC_STRING(pktS19PacketEntityStatus, "S19PacketEntityStatus")
    TRACKED_STATIC_STRING(pktS1BPacketEntityAttach, "S1BPacketEntityAttach")
    TRACKED_STATIC_STRING(pktS27PacketExplosion, "S27PacketExplosion")
    TRACKED_STATIC_STRING(pktS2BPacketChangeGameState, "S2BPacketChangeGameState")
    TRACKED_STATIC_STRING(pktS00PacketKeepAlive, "S00PacketKeepAlive")
    TRACKED_STATIC_STRING(pktS21PacketChunkData, "S21PacketChunkData")
    TRACKED_STATIC_STRING(pktS26PacketMapChunkBulk, "S26PacketMapChunkBulk")
    TRACKED_STATIC_STRING(pktS28PacketEffect, "S28PacketEffect")
    TRACKED_STATIC_STRING(pktS14PacketEntity, "S14PacketEntity")
    TRACKED_STATIC_STRING(pktS08PacketPlayerPosLook, "S08PacketPlayerPosLook")
    TRACKED_STATIC_STRING(pktS2APacketParticles, "S2APacketParticles")
    TRACKED_STATIC_STRING(pktS39PacketPlayerAbilities, "S39PacketPlayerAbilities")
    TRACKED_STATIC_STRING(pktS38PacketPlayerListItem, "S38PacketPlayerListItem")
    TRACKED_STATIC_STRING(pktS13PacketDestroyEntities, "S13PacketDestroyEntities")
    TRACKED_STATIC_STRING(pktS1EPacketRemoveEntityEffect, "S1EPacketRemoveEntityEffect")
    TRACKED_STATIC_STRING(pktS07PacketRespawn, "S07PacketRespawn")
    TRACKED_STATIC_STRING(pktS19PacketEntityHeadLook, "S19PacketEntityHeadLook")
    TRACKED_STATIC_STRING(pktS09PacketHeldItemChange, "S09PacketHeldItemChange")
    TRACKED_STATIC_STRING(pktS3DPacketDisplayScoreboard, "S3DPacketDisplayScoreboard")
    TRACKED_STATIC_STRING(pktS1CPacketEntityMetadata, "S1CPacketEntityMetadata")
    TRACKED_STATIC_STRING(pktS12PacketEntityVelocity, "S12PacketEntityVelocity")
    TRACKED_STATIC_STRING(pktS04PacketEntityEquipment, "S04PacketEntityEquipment")
    TRACKED_STATIC_STRING(pktS1FPacketSetExperience, "S1FPacketSetExperience")
    TRACKED_STATIC_STRING(pktS06PacketUpdateHealth, "S06PacketUpdateHealth")
    TRACKED_STATIC_STRING(pktS3EPacketTeams, "S3EPacketTeams")
    TRACKED_STATIC_STRING(pktS3CPacketUpdateScore, "S3CPacketUpdateScore")
    TRACKED_STATIC_STRING(pktS05PacketSpawnPosition, "S05PacketSpawnPosition")
    TRACKED_STATIC_STRING(pktS03PacketTimeUpdate, "S03PacketTimeUpdate")
    TRACKED_STATIC_STRING(pktS33PacketUpdateSign, "S33PacketUpdateSign")
    TRACKED_STATIC_STRING(pktS29PacketSoundEffect, "S29PacketSoundEffect")
    TRACKED_STATIC_STRING(pktS0DPacketCollectItem, "S0DPacketCollectItem")
    TRACKED_STATIC_STRING(pktS18PacketEntityTeleport, "S18PacketEntityTeleport")
    TRACKED_STATIC_STRING(pktS20PacketEntityProperties, "S20PacketEntityProperties")
    TRACKED_STATIC_STRING(pktS1DPacketEntityEffect, "S1DPacketEntityEffect")

    #ifdef WHIP_DEV_MODE
        TRACKED_STATIC_STRING(authServerPort, "7778")
    #else
        TRACKED_STATIC_STRING(authServerPort, "7777")
    #endif
    TRACKED_STATIC_STRING(fileKeyVersions, "versions")
    TRACKED_STATIC_STRING(fileKeyMappingsV1_7, "mappings-v1_7")
    TRACKED_STATIC_STRING(fileKeyMappingsV1_8, "mappings-v1_8")

    TRACKED_STATIC_STRING(providerVisual, "Visual Provider")
    TRACKED_STATIC_STRING(providerHUD, "HUD Provider")
    TRACKED_STATIC_STRING(providerPacket, "Packet")
    TRACKED_STATIC_STRING(providerGameState, "Game State")
    TRACKED_STATIC_STRING(providerInvalid, "Invalid")
    TRACKED_STATIC_STRING(providerUnknown, "Unknown")

    TRACKED_STATIC_STRING(sysDebuggerDetected, "Debugger detected")
    TRACKED_STATIC_STRING(sysKernel32LoadFailed, "Failed to load kernel32.dll")
    TRACKED_STATIC_STRING(sysFreeLibraryNotFound, "Failed to find FreeLibraryAndExitThreadFunction")
}

#undef TRACKED_STATIC_STRING
