// ===== file: antidebug/core/api_hash.h =====
//
// Hash-based Win32 API resolver — real import obfuscation.
//
// Purpose
// -------
// Eliminate plaintext API names and IAT entries for any Win32 function we
// call. Instead of `LoadLibraryA(...)` (which leaves "LoadLibraryA" in the
// import table and "kernel32.dll" in .idata), we resolve the function at
// runtime via:
//
//   1. Walk PEB.Ldr.InMemoryOrderModuleList, hash each BaseDllName (lower-
//      case UTF-16), match against the requested module hash → module base.
//   2. Parse the module's IMAGE_EXPORT_DIRECTORY, hash each name in
//      AddressOfNames (ASCII), match against the requested function hash →
//      function pointer.
//
// Result: no IAT entry, no plaintext "kernel32.dll" / "LoadLibraryA" in
// .rdata, nothing for `dumpbin /imports` or IDA's import view to display.
// A reverser must compute the same hashes by hand to identify which APIs
// are touched, then cross-reference call sites manually.
//
// The hash is FNV-1a 32-bit. It is small, has no constants beyond the
// prime, and runs at compile time inside the helper macro `AD_HASH(s)`
// (which is a const expression on any modern MSVC/clang build because the
// optimiser folds the loop). For maximum portability the macro is also
// available as the function `ad_hash_str` for runtime use.
//
// Usage
// -----
//   typedef int (*FN_MessageBoxA)(void*, const char*, const char*, u32);
//
//   FN_MessageBoxA pMessageBoxA = (FN_MessageBoxA)
//       ad_resolve_api(AD_HASH_USER32, AD_HASH("MessageBoxA"));
//   if (pMessageBoxA)
//       pMessageBoxA(0, "hello", "world", 0);
//
// Each (module_hash, func_hash) pair is cached in a small fixed-size LRU,
// so repeated calls take a single comparison + indirect load.
//
#ifndef ANTIDEBUG_API_HASH_H
#define ANTIDEBUG_API_HASH_H

#include "types.h"
#include "macros.h"

// ---------------------------------------------------------------------------
// FNV-1a 32-bit
// ---------------------------------------------------------------------------
#define AD_FNV_OFFSET   0x811C9DC5u
#define AD_FNV_PRIME    0x01000193u

// Runtime hash of an ASCII NUL-terminated string (case-insensitive: lowered).
ANTIDEBUG_INLINE u32 ad_hash_str(const char* s) {
    u32 h = AD_FNV_OFFSET;
    while (*s) {
        u8 c = (u8)*s++;
        if (c >= 'A' && c <= 'Z') c = (u8)(c + 32);
        h ^= c;
        h *= AD_FNV_PRIME;
    }
    return h;
}

// Runtime hash of a UTF-16 (wide) string given length in chars.
// Case-insensitive ASCII fold; non-ASCII bytes pass through.
ANTIDEBUG_INLINE u32 ad_hash_wstr(const u16* w, u32 char_count) {
    u32 h = AD_FNV_OFFSET;
    u32 i;
    for (i = 0; i < char_count; i++) {
        u16 c = w[i];
        if (c >= 'A' && c <= 'Z') c = (u16)(c + 32);
        h ^= (u8)(c & 0xFFu);
        h *= AD_FNV_PRIME;
        h ^= (u8)((c >> 8) & 0xFFu);
        h *= AD_FNV_PRIME;
    }
    return h;
}

// Compile-time-foldable hash of a string literal. The optimizer collapses
// the loop into a constant on /O2. For paranoid builds where you want
// guaranteed compile-time evaluation, precompute the hash and use the
// numeric value directly.
#define AD_HASH(s)   (ad_hash_str(s))

// Pre-computed hashes for common modules (lowercase, UTF-16-folded).
// Generated by ad_hash_wstr on lowercase L"<name>".
//   "ntdll.dll"     -> 0x?
//   "kernel32.dll"  -> 0x?
//   "user32.dll"    -> 0x?
//   "kernelbase.dll"-> 0x?
// We do NOT hard-code the values — they are computed once at first use
// and cached, so the binary contains no recognizable module-name constants.
// If you want truly literal-free code, hash a small lowercased wchar_t
// literal in your call site:
//   static const u16 wkernel32[] = { 'k','e','r','n','e','l','3','2','.','d','l','l',0 };
//   u32 h = ad_hash_wstr(wkernel32, 12);
//
// To make this ergonomic, the helpers below build the hash on the stack
// from a tiny char-by-char literal so the source string never touches the
// final binary as a contiguous blob.
#define AD_HASH_NTDLL       ad_hash_module_ntdll()
#define AD_HASH_KERNEL32    ad_hash_module_kernel32()
#define AD_HASH_KERNELBASE  ad_hash_module_kernelbase()
#define AD_HASH_USER32      ad_hash_module_user32()

ANTIDEBUG_INLINE u32 ad_hash_module_ntdll(void) {
    static u32 h = 0;
    if (!h) {
        u16 w[10];
        w[0]='n'; w[1]='t'; w[2]='d'; w[3]='l'; w[4]='l';
        w[5]='.'; w[6]='d'; w[7]='l'; w[8]='l'; w[9]=0;
        h = ad_hash_wstr(w, 9);
    }
    return h;
}
ANTIDEBUG_INLINE u32 ad_hash_module_kernel32(void) {
    static u32 h = 0;
    if (!h) {
        u16 w[13];
        w[0]='k'; w[1]='e'; w[2]='r'; w[3]='n'; w[4]='e';
        w[5]='l'; w[6]='3'; w[7]='2'; w[8]='.'; w[9]='d';
        w[10]='l'; w[11]='l'; w[12]=0;
        h = ad_hash_wstr(w, 12);
    }
    return h;
}
ANTIDEBUG_INLINE u32 ad_hash_module_kernelbase(void) {
    static u32 h = 0;
    if (!h) {
        u16 w[15];
        w[0]='k'; w[1]='e'; w[2]='r'; w[3]='n'; w[4]='e';
        w[5]='l'; w[6]='b'; w[7]='a'; w[8]='s'; w[9]='e';
        w[10]='.'; w[11]='d'; w[12]='l'; w[13]='l'; w[14]=0;
        h = ad_hash_wstr(w, 14);
    }
    return h;
}
ANTIDEBUG_INLINE u32 ad_hash_module_user32(void) {
    static u32 h = 0;
    if (!h) {
        u16 w[11];
        w[0]='u'; w[1]='s'; w[2]='e'; w[3]='r'; w[4]='3';
        w[5]='2'; w[6]='.'; w[7]='d'; w[8]='l'; w[9]='l'; w[10]=0;
        h = ad_hash_wstr(w, 10);
    }
    return h;
}

// ---------------------------------------------------------------------------
// PE export-table walker
// ---------------------------------------------------------------------------
ANTIDEBUG_INLINE void* ad_pe_resolve_export(u8* base, u32 func_hash) {
    if (!base || *(u16*)base != 0x5A4D) return 0;
    u32 pe_off = *(u32*)(base + 0x3C);
    u8* pe = base + pe_off;
    if (*(u32*)pe != 0x00004550u) return 0;

    // OptionalHeader at pe + 24. Export Directory RVA is the first
    // DataDirectory entry, which on PE32+ sits at offset 24 + 112.
    u32 export_rva  = *(u32*)(pe + 24 + 112);
    u32 export_size = *(u32*)(pe + 24 + 116);
    if (!export_rva || !export_size) return 0;

    u8* exp = base + export_rva;
    u32 num_names    = *(u32*)(exp + 24);
    u32 funcs_rva    = *(u32*)(exp + 28);
    u32 names_rva    = *(u32*)(exp + 32);
    u32 ordinals_rva = *(u32*)(exp + 36);

    u32* funcs    = (u32*)(base + funcs_rva);
    u32* names    = (u32*)(base + names_rva);
    u16* ordinals = (u16*)(base + ordinals_rva);

    u32 i;
    for (i = 0; i < num_names; i++) {
        const char* name = (const char*)(base + names[i]);
        if (ad_hash_str(name) == func_hash) {
            u16 ord = ordinals[i];
            u32 rva = funcs[ord];
            // Skip forwarders (RVA inside the export directory itself).
            if (rva >= export_rva && rva < export_rva + export_size) {
                return 0;  // forwarder; caller should resolve target dll
            }
            return (void*)(base + rva);
        }
    }
    return 0;
}

// ---------------------------------------------------------------------------
// Module finder via PEB.Ldr.InMemoryOrderModuleList
// ---------------------------------------------------------------------------
ANTIDEBUG_INLINE u8* ad_find_module_by_hash(u32 module_hash) {
#ifdef _MSC_VER
    u8* peb = (u8*)__readgsqword(0x60);
    if (!peb) return 0;
    u8* ldr = *(u8**)(peb + 0x18);
    if (!ldr) return 0;

    // InMemoryOrderModuleList head sits at ldr + 0x20 (LIST_ENTRY).
    u8* head = ldr + 0x20;
    u8* cur  = *(u8**)head;
    u32 walks = 0;

    while (cur && cur != head && walks < 256u) {
        // LDR_DATA_TABLE_ENTRY starts 0x10 bytes BEFORE InMemoryOrderLinks
        // (InLoadOrderLinks at +0x00, InMemoryOrderLinks at +0x10).
        u8* entry = cur - 0x10;
        void* dll_base = *(void**)(entry + 0x30);

        // BaseDllName UNICODE_STRING at offset +0x58 of LDR_DATA_TABLE_ENTRY.
        // struct: u16 Length, u16 MaximumLength, u32 _pad, u16* Buffer
        u16  name_len_bytes = *(u16*)(entry + 0x58);
        u16* name_buf       = *(u16**)(entry + 0x60);

        if (dll_base && name_buf && name_len_bytes >= 2u) {
            u32 name_chars = (u32)(name_len_bytes / 2u);
            if (ad_hash_wstr(name_buf, name_chars) == module_hash) {
                return (u8*)dll_base;
            }
        }

        cur = *(u8**)cur;  // Flink
        walks++;
    }
    return 0;
#else
    AD_UNUSED(module_hash);
    return 0;
#endif
}

// ---------------------------------------------------------------------------
// Resolver with small LRU cache
// ---------------------------------------------------------------------------
#define AD_API_CACHE_SLOTS 16

typedef struct {
    u32   mod_hash;
    u32   func_hash;
    void* fn;
} ad_api_cache_entry_t;

static ad_api_cache_entry_t ad_api_cache[AD_API_CACHE_SLOTS] = {0};
static u32                  ad_api_cache_pos = 0;

ANTIDEBUG_INLINE void* ad_resolve_api(u32 module_hash, u32 func_hash) {
    // Cache probe — linear, but only 16 slots, fits in two cache lines.
    u32 i;
    for (i = 0; i < AD_API_CACHE_SLOTS; i++) {
        if (ad_api_cache[i].mod_hash  == module_hash &&
            ad_api_cache[i].func_hash == func_hash &&
            ad_api_cache[i].fn) {
            return ad_api_cache[i].fn;
        }
    }

    u8* base = ad_find_module_by_hash(module_hash);
    if (!base) return 0;

    void* fn = ad_pe_resolve_export(base, func_hash);
    if (!fn) return 0;

    // Insert into cache (round-robin replacement).
    u32 slot = ad_api_cache_pos & (AD_API_CACHE_SLOTS - 1u);
    ad_api_cache[slot].mod_hash  = module_hash;
    ad_api_cache[slot].func_hash = func_hash;
    ad_api_cache[slot].fn        = fn;
    ad_api_cache_pos++;
    return fn;
}

// Convenience macro: cast directly to a function-pointer type.
//   FN_MessageBoxA p = AD_API(FN_MessageBoxA, AD_HASH_USER32, AD_HASH("MessageBoxA"));
#define AD_API(fn_type, mod_hash, func_hash) \
    ((fn_type)ad_resolve_api((mod_hash), (func_hash)))

#endif // ANTIDEBUG_API_HASH_H
