name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild "WhipClient-master/WhipClient-master/WhipClient.sln" /p:Configuration=Release /p:Platform=x64

      - uses: actions/upload-artifact@v4
        with:
          name: WhipClient
          path: WhipClient-master/WhipClient-master/**/Release/**
